env:
  browser: true
  es6: true
extends: 'eslint:recommended'
parserOptions:
  sourceType: module
rules:
  indent:
    - error
    - tab
  no-console: off
  quotes:
    - error
    - single
  semi:
    - error
    - always
